name: Cache Image
on:
  push:
    branches:
      - master
jobs:
  image-cache:
    name: Cache Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        registry: ghcr.io
        image_name: cpp-py-formatter
        image_tag: latest
        username: pgrete
        password: ${{ secrets.GHCR_TOKEN }}
        push_git_tag: true
