name: Cache Image
on:
  push:
    branches:
      - master
jobs:
  image-cache:
    name: Cache Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - uses: whoan/docker-build-with-cache-action@v8
      with:
        image_name: joshuasbrown/cpp-py-formatter
        image_tag: latest
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        push_git_tag: true
